module.exports = {
  "env": {
    "es6": true,
  },
  "rules": {
    // Errors
    "eqeqeq": ["error", "smart"],
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-func-assign": "error",
    "no-irregular-whitespace": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-sparse-arrays": "error",
    "no-undef": "error",
    "no-unused-vars": "error",
    "no-use-before-define": ["error", "nofunc"],
    "no-var": "error",
    // Warnings
    "arrow-parens": ["warn", "always"],
    "arrow-spacing": ["warn", {"before": true, "after": true}],
    "block-spacing": ["warn", "never"],
    "brace-style": ["warn", "1tbs"],
    "comma-dangle": ["warn", "always-multiline"],
    "comma-spacing": ["warn", {"before": false, "after": true}],
    "curly": ["warn", "multi-line"],
    "dot-location": ["warn", "property"],
    "no-console": "warn",
    "no-constant-condition": "warn",
    "no-extra-semi": "warn",
    "no-fallthrough": "warn",
    "no-multiple-empty-lines": ["warn", {"max": 1}],
    "no-trailing-spaces": "warn",
    "no-unneeded-ternary": "warn",
    "object-shorthand": "warn",
    "prefer-arrow-callback": "warn",
    "prefer-const": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
  }
}
